package claudemux

import (
	"errors"
	"fmt"
	"regexp"
	"strings"
)

var (
	// ErrNoModels is returned when a model menu has no detected models.
	ErrNoModels = errors.New("claudemux: no models detected in menu")
	// ErrModelNotFound is returned when the target model is not in the menu.
	ErrModelNotFound = errors.New("claudemux: target model not found in menu")
	// ErrNavigationTooLong is returned when the navigation distance exceeds
	// the safety limit, likely indicating a parsing error.
	ErrNavigationTooLong = errors.New("claudemux: navigation requires too many steps")
)

// MaxNavigationSteps is the safety limit on arrow key presses generated by
// NavigateToModel. Menus larger than this are likely parsing artifacts.
const MaxNavigationSteps = 100

// TUI navigation keystroke constants (ANSI escape sequences).
const (
	KeyArrowUp   = "\x1b[A"
	KeyArrowDown = "\x1b[B"
	KeyEnter     = "\r"
)

// ModelMenu represents the parsed state of a model selection TUI menu.
type ModelMenu struct {
	// Models lists available model names in display order.
	Models []string
	// SelectedIndex is the 0-based index of the currently highlighted model.
	// -1 means no model is currently indicated as selected.
	SelectedIndex int
}

var (
	// reSelectedArrow matches lines like "> model-name", "❯ model-name",
	// "▸ model-name", "→ model-name", or "► model-name".
	// Supported indicators: > (ASCII), ❯ (U+276F), ▸ (U+25B8 Ollama),
	// → (U+2192), ► (U+25BA).
	reSelectedArrow = regexp.MustCompile(`^\s*[❯>▸→►]\s+(\S.+?)\s*$`)
	// reNumberedItem matches "1) model" or "1. model" (numbered list entries).
	reNumberedItem = regexp.MustCompile(`^\s*(\d+)[.)]\s+(\S.+?)\s*$`)
	// reUnselectedItem matches indented model names without selection indicator.
	// Only used when context confirms we are inside a model menu.
	reUnselectedItem = regexp.MustCompile(`^\s{2,}(\S.+?)\s*$`)
)

// ParseModelMenu extracts model menu state from a sequence of terminal output
// lines. It recognizes:
//   - Arrow-key selection menus (❯ or > indicator for selected item)
//   - Numbered lists (1) model or 1. model)
//   - Plain indented model name lists
//
// Lines that do not match any model item pattern are ignored. The returned
// ModelMenu may have an empty Models slice if no items were detected.
//
// A two-pass approach is used: the first pass checks for any explicit
// indicator (selection arrow or numbered item). If found, the second pass
// also recognizes indented lines without indicators as model names. This
// prevents false positives on random indented text while correctly parsing
// menus where unselected items appear before the selected one.
func ParseModelMenu(lines []string) *ModelMenu {
	menu := &ModelMenu{SelectedIndex: -1}

	// First pass: check if any line has a selection indicator or numbered item.
	hasIndicator := false
	for _, line := range lines {
		if reSelectedArrow.MatchString(line) || reNumberedItem.MatchString(line) {
			hasIndicator = true
			break
		}
	}

	// Second pass: parse all items.
	for _, line := range lines {
		// Check for selected arrow indicator (>, ❯, ▸, →, ►).
		if m := reSelectedArrow.FindStringSubmatch(line); m != nil {
			menu.SelectedIndex = len(menu.Models)
			menu.Models = append(menu.Models, strings.TrimSpace(m[1]))
			continue
		}

		// Check for numbered items (1) model or 1. model).
		if m := reNumberedItem.FindStringSubmatch(line); m != nil {
			menu.Models = append(menu.Models, strings.TrimSpace(m[2]))
			continue
		}

		// Check for unselected indented items. Only enabled when we have
		// confirmed this block contains a model menu (via indicators).
		if hasIndicator {
			if m := reUnselectedItem.FindStringSubmatch(line); m != nil {
				menu.Models = append(menu.Models, strings.TrimSpace(m[1]))
				continue
			}
		}
	}

	return menu
}

// NavigateToModel generates the keystroke sequence needed to navigate from
// the current selection to the target model and press enter.
//
// Model matching is attempted in order: exact match, case-insensitive match,
// then substring match (case-insensitive).
//
// Returns ErrNoModels if the menu has no models.
// Returns ErrModelNotFound if the target is not in the menu.
// Returns ErrNavigationTooLong if the distance exceeds MaxNavigationSteps.
//
// If the menu has exactly one model, returns KeyEnter regardless of target
// name (auto-select behavior for single-model menus).
func NavigateToModel(menu *ModelMenu, target string) (string, error) {
	if len(menu.Models) == 0 {
		return "", ErrNoModels
	}

	// Single model: auto-select.
	if len(menu.Models) == 1 {
		return KeyEnter, nil
	}

	targetIdx := findModelIndex(menu.Models, target)
	if targetIdx < 0 {
		return "", fmt.Errorf("%w: %q (available: %s)", ErrModelNotFound, target, strings.Join(menu.Models, ", "))
	}

	// Calculate navigation from current position.
	currentIdx := menu.SelectedIndex
	if currentIdx < 0 {
		currentIdx = 0 // Assume first item is selected if none marked.
	}

	diff := targetIdx - currentIdx
	absDiff := diff
	if absDiff < 0 {
		absDiff = -absDiff
	}
	if absDiff > MaxNavigationSteps {
		return "", fmt.Errorf("%w: %d steps required", ErrNavigationTooLong, absDiff)
	}

	var keystrokes strings.Builder
	if diff > 0 {
		for i := 0; i < diff; i++ {
			keystrokes.WriteString(KeyArrowDown)
		}
	} else if diff < 0 {
		for i := 0; i < -diff; i++ {
			keystrokes.WriteString(KeyArrowUp)
		}
	}
	keystrokes.WriteString(KeyEnter)

	return keystrokes.String(), nil
}

// findModelIndex searches for a model name in a slice using progressively
// looser matching: exact, case-insensitive, then substring.
// Returns -1 if no match is found.
func findModelIndex(models []string, target string) int {
	// Exact match.
	for i, m := range models {
		if m == target {
			return i
		}
	}

	// Case-insensitive match.
	targetLower := strings.ToLower(target)
	for i, m := range models {
		if strings.ToLower(m) == targetLower {
			return i
		}
	}

	// Substring match (case-insensitive).
	for i, m := range models {
		if strings.Contains(strings.ToLower(m), targetLower) {
			return i
		}
	}

	return -1
}
