// Code generated by generate-bubbletea-key-mapping. DO NOT EDIT.

package bubbletea

// KeyDef represents metadata about a bubbletea key.
type KeyDef struct {
	// Name is the Go constant name (e.g., "KeyEnter").
	Name string
	// String is the string representation from Key.String() (e.g., "enter").
	String string
	// Code is the actual rune code value.
	Code rune
}

// KeyDefs contains all bubbletea key definitions.
// The map is keyed by the String() representation for JS lookup efficiency.
// When multiple key constants produce the same string, a canonical name is chosen.
var KeyDefs = map[string]KeyDef{
	"backspace":          {Name: "KeyBackspace", String: "backspace", Code: '\x7f'},
	"begin":              {Name: "KeyBegin", String: "begin", Code: '�'},
	"caps lock":          {Name: "KeyCapsLock", String: "caps lock", Code: '�'},
	"ctrl+\\":            {Name: "KeyCtrlBackslash", String: "ctrl+\\", Code: '\\'},
	"ctrl+]":             {Name: "KeyCtrlCloseBracket", String: "ctrl+]", Code: ']'},
	"ctrl+^":             {Name: "KeyCtrlCaret", String: "ctrl+^", Code: '^'},
	"ctrl+_":             {Name: "KeyCtrlUnderscore", String: "ctrl+_", Code: '_'},
	"ctrl+a":             {Name: "KeyCtrlA", String: "ctrl+a", Code: 'a'},
	"ctrl+b":             {Name: "KeyCtrlB", String: "ctrl+b", Code: 'b'},
	"ctrl+c":             {Name: "KeyCtrlC", String: "ctrl+c", Code: 'c'},
	"ctrl+d":             {Name: "KeyCtrlD", String: "ctrl+d", Code: 'd'},
	"ctrl+e":             {Name: "KeyCtrlE", String: "ctrl+e", Code: 'e'},
	"ctrl+f":             {Name: "KeyCtrlF", String: "ctrl+f", Code: 'f'},
	"ctrl+g":             {Name: "KeyCtrlG", String: "ctrl+g", Code: 'g'},
	"ctrl+h":             {Name: "KeyCtrlH", String: "ctrl+h", Code: 'h'},
	"ctrl+j":             {Name: "KeyCtrlJ", String: "ctrl+j", Code: 'j'},
	"ctrl+k":             {Name: "KeyCtrlK", String: "ctrl+k", Code: 'k'},
	"ctrl+l":             {Name: "KeyCtrlL", String: "ctrl+l", Code: 'l'},
	"ctrl+n":             {Name: "KeyCtrlN", String: "ctrl+n", Code: 'n'},
	"ctrl+o":             {Name: "KeyCtrlO", String: "ctrl+o", Code: 'o'},
	"ctrl+p":             {Name: "KeyCtrlP", String: "ctrl+p", Code: 'p'},
	"ctrl+q":             {Name: "KeyCtrlQ", String: "ctrl+q", Code: 'q'},
	"ctrl+r":             {Name: "KeyCtrlR", String: "ctrl+r", Code: 'r'},
	"ctrl+s":             {Name: "KeyCtrlS", String: "ctrl+s", Code: 's'},
	"ctrl+t":             {Name: "KeyCtrlT", String: "ctrl+t", Code: 't'},
	"ctrl+u":             {Name: "KeyCtrlU", String: "ctrl+u", Code: 'u'},
	"ctrl+v":             {Name: "KeyCtrlV", String: "ctrl+v", Code: 'v'},
	"ctrl+w":             {Name: "KeyCtrlW", String: "ctrl+w", Code: 'w'},
	"ctrl+x":             {Name: "KeyCtrlX", String: "ctrl+x", Code: 'x'},
	"ctrl+y":             {Name: "KeyCtrlY", String: "ctrl+y", Code: 'y'},
	"ctrl+z":             {Name: "KeyCtrlZ", String: "ctrl+z", Code: 'z'},
	"ctrl:@":             {Name: "KeyCtrlAt", String: "ctrl:@", Code: '@'},
	"delete":             {Name: "KeyDelete", String: "delete", Code: '�'},
	"down":               {Name: "KeyDown", String: "down", Code: '�'},
	"end":                {Name: "KeyEnd", String: "end", Code: '�'},
	"enter":              {Name: "KeyEnter", String: "enter", Code: '\r'},
	"esc":                {Name: "KeyEscape", String: "esc", Code: '\x1b'},
	"extended":           {Name: "KeyExtended", String: "extended", Code: '�'},
	"f1":                 {Name: "KeyF1", String: "f1", Code: '�'},
	"f10":                {Name: "KeyF10", String: "f10", Code: '�'},
	"f11":                {Name: "KeyF11", String: "f11", Code: '�'},
	"f12":                {Name: "KeyF12", String: "f12", Code: '�'},
	"f13":                {Name: "KeyF13", String: "f13", Code: '�'},
	"f14":                {Name: "KeyF14", String: "f14", Code: '�'},
	"f15":                {Name: "KeyF15", String: "f15", Code: '�'},
	"f16":                {Name: "KeyF16", String: "f16", Code: '�'},
	"f17":                {Name: "KeyF17", String: "f17", Code: '�'},
	"f18":                {Name: "KeyF18", String: "f18", Code: '�'},
	"f19":                {Name: "KeyF19", String: "f19", Code: '�'},
	"f2":                 {Name: "KeyF2", String: "f2", Code: '�'},
	"f20":                {Name: "KeyF20", String: "f20", Code: '�'},
	"f21":                {Name: "KeyF21", String: "f21", Code: '�'},
	"f22":                {Name: "KeyF22", String: "f22", Code: '�'},
	"f23":                {Name: "KeyF23", String: "f23", Code: '�'},
	"f24":                {Name: "KeyF24", String: "f24", Code: '�'},
	"f25":                {Name: "KeyF25", String: "f25", Code: '�'},
	"f26":                {Name: "KeyF26", String: "f26", Code: '�'},
	"f27":                {Name: "KeyF27", String: "f27", Code: '�'},
	"f28":                {Name: "KeyF28", String: "f28", Code: '�'},
	"f29":                {Name: "KeyF29", String: "f29", Code: '�'},
	"f3":                 {Name: "KeyF3", String: "f3", Code: '�'},
	"f30":                {Name: "KeyF30", String: "f30", Code: '�'},
	"f31":                {Name: "KeyF31", String: "f31", Code: '�'},
	"f32":                {Name: "KeyF32", String: "f32", Code: '�'},
	"f33":                {Name: "KeyF33", String: "f33", Code: '�'},
	"f34":                {Name: "KeyF34", String: "f34", Code: '�'},
	"f35":                {Name: "KeyF35", String: "f35", Code: '�'},
	"f36":                {Name: "KeyF36", String: "f36", Code: '�'},
	"f37":                {Name: "KeyF37", String: "f37", Code: '�'},
	"f38":                {Name: "KeyF38", String: "f38", Code: '�'},
	"f39":                {Name: "KeyF39", String: "f39", Code: '�'},
	"f4":                 {Name: "KeyF4", String: "f4", Code: '�'},
	"f40":                {Name: "KeyF40", String: "f40", Code: '�'},
	"f41":                {Name: "KeyF41", String: "f41", Code: '�'},
	"f42":                {Name: "KeyF42", String: "f42", Code: '�'},
	"f43":                {Name: "KeyF43", String: "f43", Code: '�'},
	"f44":                {Name: "KeyF44", String: "f44", Code: '�'},
	"f45":                {Name: "KeyF45", String: "f45", Code: '�'},
	"f46":                {Name: "KeyF46", String: "f46", Code: '�'},
	"f47":                {Name: "KeyF47", String: "f47", Code: '�'},
	"f48":                {Name: "KeyF48", String: "f48", Code: '�'},
	"f49":                {Name: "KeyF49", String: "f49", Code: '�'},
	"f5":                 {Name: "KeyF5", String: "f5", Code: '�'},
	"f50":                {Name: "KeyF50", String: "f50", Code: '�'},
	"f51":                {Name: "KeyF51", String: "f51", Code: '�'},
	"f52":                {Name: "KeyF52", String: "f52", Code: '�'},
	"f53":                {Name: "KeyF53", String: "f53", Code: '�'},
	"f54":                {Name: "KeyF54", String: "f54", Code: '�'},
	"f55":                {Name: "KeyF55", String: "f55", Code: '�'},
	"f56":                {Name: "KeyF56", String: "f56", Code: '�'},
	"f57":                {Name: "KeyF57", String: "f57", Code: '�'},
	"f58":                {Name: "KeyF58", String: "f58", Code: '�'},
	"f59":                {Name: "KeyF59", String: "f59", Code: '�'},
	"f6":                 {Name: "KeyF6", String: "f6", Code: '�'},
	"f60":                {Name: "KeyF60", String: "f60", Code: '�'},
	"f61":                {Name: "KeyF61", String: "f61", Code: '�'},
	"f62":                {Name: "KeyF62", String: "f62", Code: '�'},
	"f63":                {Name: "KeyF63", String: "f63", Code: '�'},
	"f7":                 {Name: "KeyF7", String: "f7", Code: '�'},
	"f8":                 {Name: "KeyF8", String: "f8", Code: '�'},
	"f9":                 {Name: "KeyF9", String: "f9", Code: '�'},
	"find":               {Name: "KeyFind", String: "find", Code: '�'},
	"home":               {Name: "KeyHome", String: "home", Code: '�'},
	"insert":             {Name: "KeyInsert", String: "insert", Code: '�'},
	"iso level 3 shift":  {Name: "KeyIsoLevel3Shift", String: "iso level 3 shift", Code: '�'},
	"iso level 5 shift":  {Name: "KeyIsoLevel5Shift", String: "iso level 5 shift", Code: '�'},
	"kp 0":               {Name: "KeyKp0", String: "kp 0", Code: '�'},
	"kp 1":               {Name: "KeyKp1", String: "kp 1", Code: '�'},
	"kp 2":               {Name: "KeyKp2", String: "kp 2", Code: '�'},
	"kp 3":               {Name: "KeyKp3", String: "kp 3", Code: '�'},
	"kp 4":               {Name: "KeyKp4", String: "kp 4", Code: '�'},
	"kp 5":               {Name: "KeyKp5", String: "kp 5", Code: '�'},
	"kp 6":               {Name: "KeyKp6", String: "kp 6", Code: '�'},
	"kp 7":               {Name: "KeyKp7", String: "kp 7", Code: '�'},
	"kp 8":               {Name: "KeyKp8", String: "kp 8", Code: '�'},
	"kp 9":               {Name: "KeyKp9", String: "kp 9", Code: '�'},
	"kp begin":           {Name: "KeyKpBegin", String: "kp begin", Code: '�'},
	"kp comma":           {Name: "KeyKpComma", String: "kp comma", Code: '�'},
	"kp decimal":         {Name: "KeyKpDecimal", String: "kp decimal", Code: '�'},
	"kp delete":          {Name: "KeyKpDelete", String: "kp delete", Code: '�'},
	"kp divide":          {Name: "KeyKpDivide", String: "kp divide", Code: '�'},
	"kp down":            {Name: "KeyKpDown", String: "kp down", Code: '�'},
	"kp end":             {Name: "KeyKpEnd", String: "kp end", Code: '�'},
	"kp enter":           {Name: "KeyKpEnter", String: "kp enter", Code: '�'},
	"kp equal":           {Name: "KeyKpEqual", String: "kp equal", Code: '�'},
	"kp home":            {Name: "KeyKpHome", String: "kp home", Code: '�'},
	"kp insert":          {Name: "KeyKpInsert", String: "kp insert", Code: '�'},
	"kp left":            {Name: "KeyKpLeft", String: "kp left", Code: '�'},
	"kp minus":           {Name: "KeyKpMinus", String: "kp minus", Code: '�'},
	"kp multiply":        {Name: "KeyKpMultiply", String: "kp multiply", Code: '�'},
	"kp pgdown":          {Name: "KeyKpPgDown", String: "kp pgdown", Code: '�'},
	"kp pgup":            {Name: "KeyKpPgUp", String: "kp pgup", Code: '�'},
	"kp plus":            {Name: "KeyKpPlus", String: "kp plus", Code: '�'},
	"kp right":           {Name: "KeyKpRight", String: "kp right", Code: '�'},
	"kp sep":             {Name: "KeyKpSep", String: "kp sep", Code: '�'},
	"kp up":              {Name: "KeyKpUp", String: "kp up", Code: '�'},
	"left":               {Name: "KeyLeft", String: "left", Code: '�'},
	"left alt":           {Name: "KeyLeftAlt", String: "left alt", Code: '�'},
	"left ctrl":          {Name: "KeyLeftCtrl", String: "left ctrl", Code: '�'},
	"left hyper":         {Name: "KeyLeftHyper", String: "left hyper", Code: '�'},
	"left meta":          {Name: "KeyLeftMeta", String: "left meta", Code: '�'},
	"left shift":         {Name: "KeyLeftShift", String: "left shift", Code: '�'},
	"left super":         {Name: "KeyLeftSuper", String: "left super", Code: '�'},
	"lower vol":          {Name: "KeyLowerVol", String: "lower vol", Code: '�'},
	"media fast forward": {Name: "KeyMediaFastForward", String: "media fast forward", Code: '�'},
	"media next":         {Name: "KeyMediaNext", String: "media next", Code: '�'},
	"media pause":        {Name: "KeyMediaPause", String: "media pause", Code: '�'},
	"media play":         {Name: "KeyMediaPlay", String: "media play", Code: '�'},
	"media play pause":   {Name: "KeyMediaPlayPause", String: "media play pause", Code: '�'},
	"media prev":         {Name: "KeyMediaPrev", String: "media prev", Code: '�'},
	"media record":       {Name: "KeyMediaRecord", String: "media record", Code: '�'},
	"media reverse":      {Name: "KeyMediaReverse", String: "media reverse", Code: '�'},
	"media rewind":       {Name: "KeyMediaRewind", String: "media rewind", Code: '�'},
	"media stop":         {Name: "KeyMediaStop", String: "media stop", Code: '�'},
	"menu":               {Name: "KeyMenu", String: "menu", Code: '�'},
	"mute":               {Name: "KeyMute", String: "mute", Code: '�'},
	"num lock":           {Name: "KeyNumLock", String: "num lock", Code: '�'},
	"pause":              {Name: "KeyPause", String: "pause", Code: '�'},
	"pgdown":             {Name: "KeyPgDown", String: "pgdown", Code: '�'},
	"pgup":               {Name: "KeyPgUp", String: "pgup", Code: '�'},
	"print screen":       {Name: "KeyPrintScreen", String: "print screen", Code: '�'},
	"raise vol":          {Name: "KeyRaiseVol", String: "raise vol", Code: '�'},
	"right":              {Name: "KeyRight", String: "right", Code: '�'},
	"right alt":          {Name: "KeyRightAlt", String: "right alt", Code: '�'},
	"right ctrl":         {Name: "KeyRightCtrl", String: "right ctrl", Code: '�'},
	"right hyper":        {Name: "KeyRightHyper", String: "right hyper", Code: '�'},
	"right meta":         {Name: "KeyRightMeta", String: "right meta", Code: '�'},
	"right shift":        {Name: "KeyRightShift", String: "right shift", Code: '�'},
	"right super":        {Name: "KeyRightSuper", String: "right super", Code: '�'},
	"scroll lock":        {Name: "KeyScrollLock", String: "scroll lock", Code: '�'},
	"select":             {Name: "KeySelect", String: "select", Code: '�'},
	"space":              {Name: "KeySpace", String: "space", Code: ' '},
	"tab":                {Name: "KeyTab", String: "tab", Code: '\t'},
	"up":                 {Name: "KeyUp", String: "up", Code: '�'},
}

// KeyDefsByName contains all bubbletea key definitions keyed by constant name.
// Multiple constant names may map to the same key (e.g., KeyEsc and KeyEscape both map to "esc").
var KeyDefsByName = map[string]KeyDef{
	"KeyCtrlA":            KeyDefs["ctrl+a"],
	"KeyCtrlB":            KeyDefs["ctrl+b"],
	"KeyCtrlC":            KeyDefs["ctrl+c"],
	"KeyCtrlD":            KeyDefs["ctrl+d"],
	"KeyCtrlE":            KeyDefs["ctrl+e"],
	"KeyCtrlF":            KeyDefs["ctrl+f"],
	"KeyCtrlG":            KeyDefs["ctrl+g"],
	"KeyCtrlH":            KeyDefs["ctrl+h"],
	"KeyCtrlJ":            KeyDefs["ctrl+j"],
	"KeyCtrlK":            KeyDefs["ctrl+k"],
	"KeyCtrlL":            KeyDefs["ctrl+l"],
	"KeyCtrlN":            KeyDefs["ctrl+n"],
	"KeyCtrlO":            KeyDefs["ctrl+o"],
	"KeyCtrlP":            KeyDefs["ctrl+p"],
	"KeyCtrlQ":            KeyDefs["ctrl+q"],
	"KeyCtrlR":            KeyDefs["ctrl+r"],
	"KeyCtrlS":            KeyDefs["ctrl+s"],
	"KeyCtrlT":            KeyDefs["ctrl+t"],
	"KeyCtrlU":            KeyDefs["ctrl+u"],
	"KeyCtrlV":            KeyDefs["ctrl+v"],
	"KeyCtrlW":            KeyDefs["ctrl+w"],
	"KeyCtrlX":            KeyDefs["ctrl+x"],
	"KeyCtrlY":            KeyDefs["ctrl+y"],
	"KeyCtrlZ":            KeyDefs["ctrl+z"],
	"KeyCtrlAt":           KeyDefs["ctrl:@"],
	"KeyCtrlBackslash":    KeyDefs["ctrl+\\"],
	"KeyCtrlCloseBracket": KeyDefs["ctrl+]"],
	"KeyCtrlCaret":        KeyDefs["ctrl+^"],
	"KeyCtrlUnderscore":   KeyDefs["ctrl+_"],
	"KeyExtended":         KeyDefs["extended"],
	"KeyUp":               KeyDefs["up"],
	"KeyDown":             KeyDefs["down"],
	"KeyRight":            KeyDefs["right"],
	"KeyLeft":             KeyDefs["left"],
	"KeyBegin":            KeyDefs["begin"],
	"KeyFind":             KeyDefs["find"],
	"KeyInsert":           KeyDefs["insert"],
	"KeyDelete":           KeyDefs["delete"],
	"KeySelect":           KeyDefs["select"],
	"KeyPgUp":             KeyDefs["pgup"],
	"KeyPgDown":           KeyDefs["pgdown"],
	"KeyHome":             KeyDefs["home"],
	"KeyEnd":              KeyDefs["end"],
	"KeyKpEnter":          KeyDefs["kp enter"],
	"KeyKpEqual":          KeyDefs["kp equal"],
	"KeyKpMultiply":       KeyDefs["kp multiply"],
	"KeyKpPlus":           KeyDefs["kp plus"],
	"KeyKpComma":          KeyDefs["kp comma"],
	"KeyKpMinus":          KeyDefs["kp minus"],
	"KeyKpDecimal":        KeyDefs["kp decimal"],
	"KeyKpDivide":         KeyDefs["kp divide"],
	"KeyKp0":              KeyDefs["kp 0"],
	"KeyKp1":              KeyDefs["kp 1"],
	"KeyKp2":              KeyDefs["kp 2"],
	"KeyKp3":              KeyDefs["kp 3"],
	"KeyKp4":              KeyDefs["kp 4"],
	"KeyKp5":              KeyDefs["kp 5"],
	"KeyKp6":              KeyDefs["kp 6"],
	"KeyKp7":              KeyDefs["kp 7"],
	"KeyKp8":              KeyDefs["kp 8"],
	"KeyKp9":              KeyDefs["kp 9"],
	"KeyKpSep":            KeyDefs["kp sep"],
	"KeyKpUp":             KeyDefs["kp up"],
	"KeyKpDown":           KeyDefs["kp down"],
	"KeyKpLeft":           KeyDefs["kp left"],
	"KeyKpRight":          KeyDefs["kp right"],
	"KeyKpPgUp":           KeyDefs["kp pgup"],
	"KeyKpPgDown":         KeyDefs["kp pgdown"],
	"KeyKpHome":           KeyDefs["kp home"],
	"KeyKpEnd":            KeyDefs["kp end"],
	"KeyKpInsert":         KeyDefs["kp insert"],
	"KeyKpDelete":         KeyDefs["kp delete"],
	"KeyKpBegin":          KeyDefs["kp begin"],
	"KeyCapsLock":         KeyDefs["caps lock"],
	"KeyScrollLock":       KeyDefs["scroll lock"],
	"KeyNumLock":          KeyDefs["num lock"],
	"KeyPrintScreen":      KeyDefs["print screen"],
	"KeyPause":            KeyDefs["pause"],
	"KeyMenu":             KeyDefs["menu"],
	"KeyMediaPlay":        KeyDefs["media play"],
	"KeyMediaPause":       KeyDefs["media pause"],
	"KeyMediaPlayPause":   KeyDefs["media play pause"],
	"KeyMediaReverse":     KeyDefs["media reverse"],
	"KeyMediaStop":        KeyDefs["media stop"],
	"KeyMediaFastForward": KeyDefs["media fast forward"],
	"KeyMediaRewind":      KeyDefs["media rewind"],
	"KeyMediaNext":        KeyDefs["media next"],
	"KeyMediaPrev":        KeyDefs["media prev"],
	"KeyMediaRecord":      KeyDefs["media record"],
	"KeyLowerVol":         KeyDefs["lower vol"],
	"KeyRaiseVol":         KeyDefs["raise vol"],
	"KeyMute":             KeyDefs["mute"],
	"KeyLeftShift":        KeyDefs["left shift"],
	"KeyLeftAlt":          KeyDefs["left alt"],
	"KeyLeftCtrl":         KeyDefs["left ctrl"],
	"KeyLeftSuper":        KeyDefs["left super"],
	"KeyLeftHyper":        KeyDefs["left hyper"],
	"KeyLeftMeta":         KeyDefs["left meta"],
	"KeyRightShift":       KeyDefs["right shift"],
	"KeyRightAlt":         KeyDefs["right alt"],
	"KeyRightCtrl":        KeyDefs["right ctrl"],
	"KeyRightSuper":       KeyDefs["right super"],
	"KeyRightHyper":       KeyDefs["right hyper"],
	"KeyRightMeta":        KeyDefs["right meta"],
	"KeyIsoLevel3Shift":   KeyDefs["iso level 3 shift"],
	"KeyIsoLevel5Shift":   KeyDefs["iso level 5 shift"],
	"KeyBackspace":        KeyDefs["backspace"],
	"KeyTab":              KeyDefs["tab"],
	"KeyEnter":            KeyDefs["enter"],
	"KeyReturn":           KeyDefs["enter"],
	"KeyEscape":           KeyDefs["esc"],
	"KeyEsc":              KeyDefs["esc"],
	"KeySpace":            KeyDefs["space"],
	"KeyF1":               KeyDefs["f1"],
	"KeyF2":               KeyDefs["f2"],
	"KeyF3":               KeyDefs["f3"],
	"KeyF4":               KeyDefs["f4"],
	"KeyF5":               KeyDefs["f5"],
	"KeyF6":               KeyDefs["f6"],
	"KeyF7":               KeyDefs["f7"],
	"KeyF8":               KeyDefs["f8"],
	"KeyF9":               KeyDefs["f9"],
	"KeyF10":              KeyDefs["f10"],
	"KeyF11":              KeyDefs["f11"],
	"KeyF12":              KeyDefs["f12"],
	"KeyF13":              KeyDefs["f13"],
	"KeyF14":              KeyDefs["f14"],
	"KeyF15":              KeyDefs["f15"],
	"KeyF16":              KeyDefs["f16"],
	"KeyF17":              KeyDefs["f17"],
	"KeyF18":              KeyDefs["f18"],
	"KeyF19":              KeyDefs["f19"],
	"KeyF20":              KeyDefs["f20"],
	"KeyF21":              KeyDefs["f21"],
	"KeyF22":              KeyDefs["f22"],
	"KeyF23":              KeyDefs["f23"],
	"KeyF24":              KeyDefs["f24"],
	"KeyF25":              KeyDefs["f25"],
	"KeyF26":              KeyDefs["f26"],
	"KeyF27":              KeyDefs["f27"],
	"KeyF28":              KeyDefs["f28"],
	"KeyF29":              KeyDefs["f29"],
	"KeyF30":              KeyDefs["f30"],
	"KeyF31":              KeyDefs["f31"],
	"KeyF32":              KeyDefs["f32"],
	"KeyF33":              KeyDefs["f33"],
	"KeyF34":              KeyDefs["f34"],
	"KeyF35":              KeyDefs["f35"],
	"KeyF36":              KeyDefs["f36"],
	"KeyF37":              KeyDefs["f37"],
	"KeyF38":              KeyDefs["f38"],
	"KeyF39":              KeyDefs["f39"],
	"KeyF40":              KeyDefs["f40"],
	"KeyF41":              KeyDefs["f41"],
	"KeyF42":              KeyDefs["f42"],
	"KeyF43":              KeyDefs["f43"],
	"KeyF44":              KeyDefs["f44"],
	"KeyF45":              KeyDefs["f45"],
	"KeyF46":              KeyDefs["f46"],
	"KeyF47":              KeyDefs["f47"],
	"KeyF48":              KeyDefs["f48"],
	"KeyF49":              KeyDefs["f49"],
	"KeyF50":              KeyDefs["f50"],
	"KeyF51":              KeyDefs["f51"],
	"KeyF52":              KeyDefs["f52"],
	"KeyF53":              KeyDefs["f53"],
	"KeyF54":              KeyDefs["f54"],
	"KeyF55":              KeyDefs["f55"],
	"KeyF56":              KeyDefs["f56"],
	"KeyF57":              KeyDefs["f57"],
	"KeyF58":              KeyDefs["f58"],
	"KeyF59":              KeyDefs["f59"],
	"KeyF60":              KeyDefs["f60"],
	"KeyF61":              KeyDefs["f61"],
	"KeyF62":              KeyDefs["f62"],
	"KeyF63":              KeyDefs["f63"],
}

// AllKeyCodes returns all known key rune values that have string representations.
// Uses canonical constant names for deterministic output.
var AllKeyCodes = []rune{
	'\x7f', // KeyBackspace
	'�',    // KeyBegin
	'�',    // KeyCapsLock
	'\\',   // KeyCtrlBackslash
	']',    // KeyCtrlCloseBracket
	'^',    // KeyCtrlCaret
	'_',    // KeyCtrlUnderscore
	'a',    // KeyCtrlA
	'b',    // KeyCtrlB
	'c',    // KeyCtrlC
	'd',    // KeyCtrlD
	'e',    // KeyCtrlE
	'f',    // KeyCtrlF
	'g',    // KeyCtrlG
	'h',    // KeyCtrlH
	'j',    // KeyCtrlJ
	'k',    // KeyCtrlK
	'l',    // KeyCtrlL
	'n',    // KeyCtrlN
	'o',    // KeyCtrlO
	'p',    // KeyCtrlP
	'q',    // KeyCtrlQ
	'r',    // KeyCtrlR
	's',    // KeyCtrlS
	't',    // KeyCtrlT
	'u',    // KeyCtrlU
	'v',    // KeyCtrlV
	'w',    // KeyCtrlW
	'x',    // KeyCtrlX
	'y',    // KeyCtrlY
	'z',    // KeyCtrlZ
	'@',    // KeyCtrlAt
	'�',    // KeyDelete
	'�',    // KeyDown
	'�',    // KeyEnd
	'\r',   // KeyEnter
	'\x1b', // KeyEscape
	'�',    // KeyExtended
	'�',    // KeyF1
	'�',    // KeyF10
	'�',    // KeyF11
	'�',    // KeyF12
	'�',    // KeyF13
	'�',    // KeyF14
	'�',    // KeyF15
	'�',    // KeyF16
	'�',    // KeyF17
	'�',    // KeyF18
	'�',    // KeyF19
	'�',    // KeyF2
	'�',    // KeyF20
	'�',    // KeyF21
	'�',    // KeyF22
	'�',    // KeyF23
	'�',    // KeyF24
	'�',    // KeyF25
	'�',    // KeyF26
	'�',    // KeyF27
	'�',    // KeyF28
	'�',    // KeyF29
	'�',    // KeyF3
	'�',    // KeyF30
	'�',    // KeyF31
	'�',    // KeyF32
	'�',    // KeyF33
	'�',    // KeyF34
	'�',    // KeyF35
	'�',    // KeyF36
	'�',    // KeyF37
	'�',    // KeyF38
	'�',    // KeyF39
	'�',    // KeyF4
	'�',    // KeyF40
	'�',    // KeyF41
	'�',    // KeyF42
	'�',    // KeyF43
	'�',    // KeyF44
	'�',    // KeyF45
	'�',    // KeyF46
	'�',    // KeyF47
	'�',    // KeyF48
	'�',    // KeyF49
	'�',    // KeyF5
	'�',    // KeyF50
	'�',    // KeyF51
	'�',    // KeyF52
	'�',    // KeyF53
	'�',    // KeyF54
	'�',    // KeyF55
	'�',    // KeyF56
	'�',    // KeyF57
	'�',    // KeyF58
	'�',    // KeyF59
	'�',    // KeyF6
	'�',    // KeyF60
	'�',    // KeyF61
	'�',    // KeyF62
	'�',    // KeyF63
	'�',    // KeyF7
	'�',    // KeyF8
	'�',    // KeyF9
	'�',    // KeyFind
	'�',    // KeyHome
	'�',    // KeyInsert
	'�',    // KeyIsoLevel3Shift
	'�',    // KeyIsoLevel5Shift
	'�',    // KeyKp0
	'�',    // KeyKp1
	'�',    // KeyKp2
	'�',    // KeyKp3
	'�',    // KeyKp4
	'�',    // KeyKp5
	'�',    // KeyKp6
	'�',    // KeyKp7
	'�',    // KeyKp8
	'�',    // KeyKp9
	'�',    // KeyKpBegin
	'�',    // KeyKpComma
	'�',    // KeyKpDecimal
	'�',    // KeyKpDelete
	'�',    // KeyKpDivide
	'�',    // KeyKpDown
	'�',    // KeyKpEnd
	'�',    // KeyKpEnter
	'�',    // KeyKpEqual
	'�',    // KeyKpHome
	'�',    // KeyKpInsert
	'�',    // KeyKpLeft
	'�',    // KeyKpMinus
	'�',    // KeyKpMultiply
	'�',    // KeyKpPgDown
	'�',    // KeyKpPgUp
	'�',    // KeyKpPlus
	'�',    // KeyKpRight
	'�',    // KeyKpSep
	'�',    // KeyKpUp
	'�',    // KeyLeft
	'�',    // KeyLeftAlt
	'�',    // KeyLeftCtrl
	'�',    // KeyLeftHyper
	'�',    // KeyLeftMeta
	'�',    // KeyLeftShift
	'�',    // KeyLeftSuper
	'�',    // KeyLowerVol
	'�',    // KeyMediaFastForward
	'�',    // KeyMediaNext
	'�',    // KeyMediaPause
	'�',    // KeyMediaPlay
	'�',    // KeyMediaPlayPause
	'�',    // KeyMediaPrev
	'�',    // KeyMediaRecord
	'�',    // KeyMediaReverse
	'�',    // KeyMediaRewind
	'�',    // KeyMediaStop
	'�',    // KeyMenu
	'�',    // KeyMute
	'�',    // KeyNumLock
	'�',    // KeyPause
	'�',    // KeyPgDown
	'�',    // KeyPgUp
	'�',    // KeyPrintScreen
	'�',    // KeyRaiseVol
	'�',    // KeyRight
	'�',    // KeyRightAlt
	'�',    // KeyRightCtrl
	'�',    // KeyRightHyper
	'�',    // KeyRightMeta
	'�',    // KeyRightShift
	'�',    // KeyRightSuper
	'�',    // KeyScrollLock
	'�',    // KeySelect
	' ',    // KeySpace
	'\t',   // KeyTab
	'�',    // KeyUp
}
