// Code generated by generate-bubbletea-key-mapping. DO NOT EDIT.

package bubbletea

import tea "charm.land/bubbletea/v2"

// MouseButtonDef represents metadata about a bubbletea MouseButton.
type MouseButtonDef struct {
	// Name is the Go constant name (e.g., "MouseLeft").
	Name string
	// String is the string representation (e.g., "left").
	String string
	// Button is the actual tea.MouseButton value.
	Button tea.MouseButton
}

// MouseButtonDefs contains all bubbletea MouseButton definitions.
// The map is keyed by the String() representation for JS lookup efficiency.
var MouseButtonDefs = map[string]MouseButtonDef{
	"backward":    {Name: "MouseBackward", String: "backward", Button: tea.MouseBackward},
	"button 10":   {Name: "MouseButton10", String: "button 10", Button: tea.MouseButton10},
	"button 11":   {Name: "MouseButton11", String: "button 11", Button: tea.MouseButton11},
	"forward":     {Name: "MouseForward", String: "forward", Button: tea.MouseForward},
	"left":        {Name: "MouseLeft", String: "left", Button: tea.MouseLeft},
	"middle":      {Name: "MouseMiddle", String: "middle", Button: tea.MouseMiddle},
	"none":        {Name: "MouseNone", String: "none", Button: tea.MouseNone},
	"right":       {Name: "MouseRight", String: "right", Button: tea.MouseRight},
	"wheel down":  {Name: "MouseWheelDown", String: "wheel down", Button: tea.MouseWheelDown},
	"wheel left":  {Name: "MouseWheelLeft", String: "wheel left", Button: tea.MouseWheelLeft},
	"wheel right": {Name: "MouseWheelRight", String: "wheel right", Button: tea.MouseWheelRight},
	"wheel up":    {Name: "MouseWheelUp", String: "wheel up", Button: tea.MouseWheelUp},
}

// MouseButtonDefsByName contains all bubbletea MouseButton definitions keyed by constant name.
var MouseButtonDefsByName = map[string]MouseButtonDef{
	"MouseBackward":   MouseButtonDefs["backward"],
	"MouseButton10":   MouseButtonDefs["button 10"],
	"MouseButton11":   MouseButtonDefs["button 11"],
	"MouseForward":    MouseButtonDefs["forward"],
	"MouseLeft":       MouseButtonDefs["left"],
	"MouseMiddle":     MouseButtonDefs["middle"],
	"MouseNone":       MouseButtonDefs["none"],
	"MouseRight":      MouseButtonDefs["right"],
	"MouseWheelDown":  MouseButtonDefs["wheel down"],
	"MouseWheelLeft":  MouseButtonDefs["wheel left"],
	"MouseWheelRight": MouseButtonDefs["wheel right"],
	"MouseWheelUp":    MouseButtonDefs["wheel up"],
}

// AllMouseButtons returns all known tea.MouseButton values that have string representations.
var AllMouseButtons = []tea.MouseButton{
	tea.MouseBackward,
	tea.MouseButton10,
	tea.MouseButton11,
	tea.MouseForward,
	tea.MouseLeft,
	tea.MouseMiddle,
	tea.MouseNone,
	tea.MouseRight,
	tea.MouseWheelDown,
	tea.MouseWheelLeft,
	tea.MouseWheelRight,
	tea.MouseWheelUp,
}

// IsWheelButton returns true if the button is a wheel button.
func IsWheelButton(b tea.MouseButton) bool {
	return b == tea.MouseWheelUp || b == tea.MouseWheelDown ||
		b == tea.MouseWheelLeft || b == tea.MouseWheelRight
}
