package bubbletea

import (
	"strings"
	"unicode/utf8"

	tea "charm.land/bubbletea/v2"
	"github.com/rivo/uniseg"
)

// ParseKey parses a string representation of a key event
// (as generated by KeyPressMsg.String()) back into a KeyPressMsg.
//
// The boolean indicates whether the parsing was unambiguous.
//
// In v2, modifier+key combinations are stored as: Code=base_rune, Mod=modifier.
// The String() method reconstructs the full representation (e.g., "ctrl+a")
// from Code+Mod. This means ParseKey must reverse that: given "ctrl+a",
// find the base key "a" and set Mod=ModCtrl.
//
// Handles:
//  1. Modifier prefixes: "ctrl+", "alt+", "shift+", "meta+", "hyper+", "super+"
//  2. Named keys via KeyDefs (e.g., "enter", "space", "tab", etc.)
//  3. Raw runes as fallback
//  4. All zero values (empty input)
//
// Note: v2 does NOT have special bracket paste syntax — bracket characters
// are treated as plain text.
func ParseKey(input string) (tea.KeyPressMsg, bool) {
	var k tea.KeyPressMsg

	if input == "" {
		return k, false
	}

	// =====================================================================
	// Step 1: Extract modifiers
	// =====================================================================
	modifiers := []struct {
		prefix string
		mod    tea.KeyMod
	}{
		{"ctrl+", tea.ModCtrl},
		{"alt+", tea.ModAlt},
		{"shift+", tea.ModShift},
		{"meta+", tea.ModMeta},
		{"hyper+", tea.ModHyper},
		{"super+", tea.ModSuper},
	}

	modStr := input
	for _, m := range modifiers {
		if strings.HasPrefix(modStr, m.prefix) {
			k.Mod |= m.mod
			modStr = modStr[len(m.prefix):]
		}
	}

	// modStr is now the key portion without modifiers

	// Empty remainder after modifier stripping → invalid (bare modifier)
	if modStr == "" {
		k.Code = 0
		k.Text = ""
		return k, false
	}

	// Second pass: if modStr still starts with a modifier prefix, strip it too.
	// This handles cases like "alt+alt+" where two modifier prefixes are chained.
	// If we find another modifier prefix in the remainder, strip it and continue.
	for _, m := range modifiers {
		if strings.HasPrefix(modStr, m.prefix) {
			k.Mod |= m.mod
			modStr = modStr[len(m.prefix):]
			break // Only strip one more prefix, not all
		}
	}

	// If stripping the second modifier left us with empty remainder,
	// it's a bare double-modifier (invalid).
	if modStr == "" {
		k.Code = 0
		k.Text = ""
		return k, false
	}

	// =====================================================================
	// Step 2: Look up base key in KeyDefs
	// If we have modifiers, also try the combined form (e.g., "ctrl+a")
	// =====================================================================
	if t, ok := KeyDefs[modStr]; ok {
		k.Code = t.Code
		k.Text = ""
		return k, true
	}

	// For modifier+key combos like "ctrl+a" where KeyDefs["a"] might exist
	// but we need to use the combined form, check if a modifier was found
	// and try the full input (modifier+key) in KeyDefs.
	// Note: This handles cases where KeyDefs has "ctrl+a" entry.
	if k.Mod != 0 {
		if t, ok := KeyDefs[input]; ok {
			k.Code = t.Code
			k.Text = ""
			return k, true
		}
	}

	// Special case: "ctrl:@" is represented as "ctrl:@" in v2 KeyDefs,
	// but the input "ctrl+@" uses a plus sign. Normalize for lookup.
	// This is unambiguous because ctrl+@ (NUL) is a control character, not text.
	if input == "ctrl+@" || input == "ctrl:@" {
		k.Code = '@'
		k.Text = ""
		return k, true
	}

	// =====================================================================
	// Step 3: Literal space character ' ' (not in KeyDefs, but is a key)
	// Handle literal space ONLY when no modifiers are present.
	// With modifiers, the input is ambiguous (could be text input with AltGr,
	// or could be a key chord). E.g., "alt+ " (Alt+Space) is ambiguous because
	// the user could be typing an accented character.
	// =====================================================================
	if modStr == " " && k.Mod == 0 {
		k.Code = ' '
		k.Text = " "
		return k, true
	}

	// =====================================================================
	// Step 4: Modifier + single character (e.g., "ctrl+a", "alt+a")
	// If we have modifiers and a single character, that's the base key.
	// For modified letters (alt+x, ctrl+x), also set Text to the letter.
	// Non-letter characters (like space, punctuation) are ambiguous when
	// combined with modifiers because they could be text input (e.g., Alt+Space
	// for accented characters, Alt+. for dead key sequences).
	// =====================================================================
	if len(modStr) == 1 && k.Mod != 0 {
		k.Code = rune(modStr[0])
		// Always preserve the text for single modified characters
		k.Text = modStr
		c := modStr[0]
		isLetter := (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z')
		// Letters are unambiguous key presses; non-letters are ambiguous
		// because they could be text input (e.g., Alt+Space for accented chars)
		return k, isLetter
	}

	// =====================================================================
	// Step 5: Raw text fallback
	// No modifier, no KeyDef match, not literal space.
	// Treat as printable text.
	// =====================================================================
	k.Code = 0
	k.Text = modStr

	// Unambiguous if single rune or single-width grapheme
	runeCount := utf8.RuneCountInString(modStr)
	return k, runeCount == 1 || (uniseg.StringWidth(modStr) == 1 && runeCount <= 2)
}
