package triage

import (
	"path/filepath"
	"regexp"
	"strings"
)

// TriageKind classifies a hunk.
type TriageKind string

const (
	Trivial          TriageKind = "TRIVIAL"
	SemanticReview   TriageKind = "SEMANTIC_REVIEW"
	HighRiskSecurity TriageKind = "HIGH_RISK_SECURITY"
)

// TriageResult is per-file triage.
type TriageResult struct {
	File   string     `json:"file"`
	Kind   TriageKind `json:"kind"`
	Reason string     `json:"reason"`
	Lines  int        `json:"lines"`
}

// TriageDiff classifies each file diff in a unified diff.
func TriageDiff(diff string) []TriageResult {
	if strings.TrimSpace(diff) == "" {
		return nil
	}
	fileDiffs := splitDiffForTriage(diff)
	var results []TriageResult
	for _, fd := range fileDiffs {
		kind, reason := classifyFile(fd.name, fd.content)
		results = append(results, TriageResult{
			File:   fd.name,
			Kind:   kind,
			Reason: reason,
			Lines:  countLinesTriage(fd.content),
		})
	}
	return results
}

// Summary returns counts per kind.
func TriageSummary(results []TriageResult) map[TriageKind]int {
	m := map[TriageKind]int{Trivial: 0, SemanticReview: 0, HighRiskSecurity: 0}
	for _, r := range results {
		m[r.Kind]++
	}
	return m
}

var (
	lockfileRe       = regexp.MustCompile(`(?i)(^|/)(package-lock\.json|yarn\.lock|pnpm-lock\.yaml|Cargo\.lock|go\.sum|poetry\.lock|Gemfile\.lock)$`)
	generatedRe      = regexp.MustCompile(`(?i)code generated|do not edit|auto-generated|generated by`)
	whitespaceOnlyRe = regexp.MustCompile(`(?m)^[+-]\s*$`)
	commentOnlyRe    = regexp.MustCompile(`(?m)^[+-]\s*(//|#|\*|<!--).*`)
	securityRe       = regexp.MustCompile(`(?i)(auth|crypto|password|secret|token|privilege|injection|sql|eval\(|exec\(|unsafe|permission)`)
)

func classifyFile(name, content string) (TriageKind, string) {
	if lockfileRe.MatchString(name) || strings.HasSuffix(name, ".lock") {
		return Trivial, "lockfile"
	}
	if generatedRe.MatchString(content) {
		return Trivial, "generated code"
	}
	lowerName := strings.ToLower(name)
	if strings.Contains(lowerName, "auth") || strings.Contains(lowerName, "crypto") || strings.Contains(lowerName, "security") || strings.Contains(lowerName, "secret") {
		if securityRe.MatchString(content) {
			return HighRiskSecurity, "security-sensitive file + risky pattern"
		}
	}
	if securityRe.MatchString(content) && containsAddedLines(content, securityRe) {
		if strings.Contains(content, "password") || strings.Contains(content, "secret") || strings.Contains(content, "eval(") || strings.Contains(content, "exec(") {
			return HighRiskSecurity, "high-risk pattern in added lines"
		}
	}
	if isWhitespaceOrCommentOnly(content) {
		return Trivial, "whitespace/comments only"
	}
	return SemanticReview, "semantic change"
}

func containsAddedLines(content string, re *regexp.Regexp) bool {
	for _, line := range strings.Split(content, "\n") {
		if strings.HasPrefix(line, "+") && re.MatchString(line) {
			return true
		}
	}
	return false
}

func isWhitespaceOrCommentOnly(content string) bool {
	lines := strings.Split(content, "\n")
	added := 0
	trivial := 0
	for _, line := range lines {
		if strings.HasPrefix(line, "+") && !strings.HasPrefix(line, "+++") {
			added++
			trimmed := strings.TrimSpace(line[1:])
			if trimmed == "" || whitespaceOnlyRe.MatchString(line) || commentOnlyRe.MatchString(line) {
				trivial++
			} else if isOnlyWhitespaceChange(line) {
				trivial++
			}
		} else if strings.HasPrefix(line, "-") && !strings.HasPrefix(line, "---") {
			added++
			trimmed := strings.TrimSpace(line[1:])
			if trimmed == "" || whitespaceOnlyRe.MatchString(line) || commentOnlyRe.MatchString(line) {
				trivial++
			}
		}
	}
	if added == 0 {
		return false
	}
	return trivial == added
}

func isOnlyWhitespaceChange(line string) bool {
	content := strings.TrimSpace(line[1:])
	if content == "" {
		return true
	}
	noSpace := strings.ReplaceAll(content, " ", "")
	noSpace = strings.ReplaceAll(noSpace, "\t", "")
	return len(noSpace) < 3
}

type triageFileDiff struct {
	name    string
	content string
}

func splitDiffForTriage(diff string) []triageFileDiff {
	const marker = "diff --git "
	var result []triageFileDiff
	lines := strings.Split(diff, "\n")
	var current []string
	started := false
	var currentName string
	flush := func() {
		if started && len(current) > 0 && currentName != "" {
			result = append(result, triageFileDiff{name: currentName, content: strings.Join(current, "\n")})
		}
	}
	for _, line := range lines {
		if strings.HasPrefix(line, marker) {
			flush()
			started = true
			current = []string{line}
			parts := strings.Split(line, " ")
			if len(parts) >= 4 {
				b := strings.TrimPrefix(parts[3], "b/")
				currentName = filepath.Clean(b)
			} else {
				currentName = line
			}
		} else if started {
			current = append(current, line)
		}
	}
	flush()
	return result
}

func countLinesTriage(s string) int {
	if s == "" {
		return 0
	}
	n := strings.Count(s, "\n")
	if !strings.HasSuffix(s, "\n") {
		n++
	}
	return n
}
