'use strict';
// pr_split_07_prcreation.js — GitHub PR creation via gh CLI
// Dependencies: chunk 00 (_gitExec, _padIndex, _modules.exec).
// Attaches to prSplit: createPRs.

(function(prSplit) {
    // Note: gitExec and exec are read at call time (late-bound) rather than
    // captured at load time. This enables test mocking since createPRs
    // involves external calls (push, gh CLI) that must be mockable.
    var padIndex = prSplit._padIndex;

    // -----------------------------------------------------------------------
    //  createPRs — pushes branches and creates stacked GitHub PRs
    // -----------------------------------------------------------------------
    // Options:
    //   draft:       bool   - Create as draft PRs (default: true)
    //   remote:      string - Git remote to push to (default: 'origin')
    //   pushOnly:    bool   - Push branches but don't create PRs
    //   autoMerge:   bool   - Enable auto-merge via merge queue
    //   mergeMethod: string - Merge method: squash, merge, rebase
    function createPRs(plan, options) {
        options = options || {};
        var resolveDir = prSplit._resolveDir;
        var dir = resolveDir(plan.dir || '.');
        var draft = options.draft !== false;
        var remote = options.remote || 'origin';
        var pushOnly = options.pushOnly || false;
        var autoMerge = options.autoMerge || false;
        var mergeMethod = options.mergeMethod || 'squash';

        if (!plan.splits || plan.splits.length === 0) {
            return { error: 'no splits in plan — run "plan" or "run" to generate splits first', results: [] };
        }

        // Late-bound references for mockability.
        var gitExec = prSplit._gitExec;
        var exec = prSplit._modules.exec;

        // Verify gh CLI is available (unless push-only mode).
        if (!pushOnly) {
            var ghCheck = exec.execv(['gh', '--version']);
            if (ghCheck.code !== 0) {
                return { error: 'gh CLI not found — install GitHub CLI (https://cli.github.com) or use --push-only', results: [] };
            }
        }

        // Pre-flight: verify baseBranch exists on the remote so we don't
        // hit "Base sha can't be blank" from the GitHub GraphQL API.
        if (!pushOnly) {
            var remoteCheck = gitExec(dir, ['ls-remote', '--heads', remote, plan.baseBranch]);
            if (remoteCheck.code !== 0 || remoteCheck.stdout.trim() === '') {
                return {
                    error: 'base branch "' + plan.baseBranch + '" not found on remote "' + remote + '" — push it first or check the branch name',
                    results: []
                };
            }
        }

        var results = [];

        // Step 1: Push all split branches.
        for (var i = 0; i < plan.splits.length; i++) {
            var split = plan.splits[i];
            var pushResult = gitExec(dir, ['push', '-f', remote, split.name]);
            if (pushResult.code !== 0) {
                results.push({
                    name: split.name,
                    pushed: false,
                    prUrl: '',
                    error: 'push failed: ' + pushResult.stderr.trim()
                });
                return { error: 'push failed for ' + split.name + ': ' + pushResult.stderr.trim(), results: results };
            }
            results.push({
                name: split.name,
                pushed: true,
                prUrl: '',
                error: null
            });
        }

        if (pushOnly) {
            return { error: null, results: results };
        }

        // Step 2: Create PRs, stacked.
        for (var pi = 0; pi < plan.splits.length; pi++) {
            var prSplit2 = plan.splits[pi];
            var base = pi === 0 ? plan.baseBranch : plan.splits[pi - 1].name;
            var title = '[' + padIndex(pi + 1) + '/' + padIndex(plan.splits.length) + '] ' + prSplit2.message;
            var body = 'Part ' + (pi + 1) + ' of ' + plan.splits.length + ' — auto-generated by `osm pr-split`.\n\n';
            body += '**Files:**\n';
            for (var j = 0; j < prSplit2.files.length; j++) {
                body += '- `' + prSplit2.files[j] + '`\n';
            }

            if (pi < plan.splits.length - 1) {
                body += '\n> ⚠️ **Stacked PR** — merge in order. Next: `' + plan.splits[pi + 1].name + '`';
            } else {
                body += '\n> ✅ **Last PR in stack** — merging this completes the split.';
            }

            var ghArgs = ['gh', 'pr', 'create',
                '--base', base,
                '--head', prSplit2.name,
                '--title', title,
                '--body', body
            ];
            if (draft) {
                ghArgs.push('--draft');
            }

            // Pre-check: verify the head branch has actual changes from
            // the base. This avoids the GraphQL error "No commits between
            // base and head" / "Head sha can't be blank" which occurs when
            // execute-split fell back to --allow-empty.
            var diffCheck = gitExec(dir, ['diff', '--quiet', base, prSplit2.name]);
            if (diffCheck.code === 0) {
                // Exit code 0 means no diff — skip PR creation.
                results[pi].error = null;
                results[pi].skipped = true;
                results[pi].skipReason = 'no changes between "' + base + '" and "' + prSplit2.name + '" — skipping PR creation';
                continue;
            }

            var ghResult = exec.execv(ghArgs);
            if (ghResult.code !== 0) {
                results[pi].error = 'gh pr create failed: ' + ghResult.stderr.trim();
            } else {
                results[pi].prUrl = ghResult.stdout.trim();
            }
        }

        // Step 3: Auto-merge via merge queue (if enabled).
        if (autoMerge) {
            for (var k = 0; k < plan.splits.length; k++) {
                var splitForMerge = plan.splits[k];
                if (results[k].error) continue;
                var mergeArgs = ['gh', 'pr', 'merge', splitForMerge.name,
                    '--' + mergeMethod,
                    '--auto'
                ];
                var mergeResult = exec.execv(mergeArgs);
                if (mergeResult.code !== 0) {
                    results[k].mergeError = 'auto-merge failed: ' + mergeResult.stderr.trim();
                } else {
                    results[k].autoMerge = true;
                }
            }
        }

        return { error: null, results: results };
    }

    // -----------------------------------------------------------------------
    //  Exports
    // -----------------------------------------------------------------------
    prSplit.createPRs = createPRs;
})(globalThis.prSplit);
