'use strict';
// pr_split_07_prcreation.js — GitHub PR creation via gh CLI
// Dependencies: chunk 00 (_gitExec, _padIndex, _modules.exec).
// Attaches to prSplit: createPRs.

(function(prSplit) {
    // Note: gitExec and exec are read at call time (late-bound) rather than
    // captured at load time. This enables test mocking since createPRs
    // involves external calls (push, gh CLI) that must be mockable.
    var padIndex = prSplit._padIndex;

    // --- formatPRTitle — formats PR title following Commit-Loom conventions ---
    function formatPRTitle(plan, splitIndex) {
        var total = plan.splits.length;
        var split = plan.splits[splitIndex];
        var text = (split && (split.title || split.message)) || ('Split ' + (splitIndex + 1));
        return '[' + padIndex(splitIndex + 1) + '/' + padIndex(total) + '] ' + text;
    }

    // --- formatPRBody — formats PR body with Commit-Loom and GitHub Stacked PR navigation ---
    function formatPRBody(plan, splitIndex) {
        var total = plan.splits.length;
        var split = plan.splits[splitIndex];
        var baseBranch = (plan && plan.baseBranch) || 'main';
        var base = splitIndex === 0 ? baseBranch : plan.splits[splitIndex - 1].name;
        var lines = [];

        // Header
        lines.push('Part ' + (splitIndex + 1) + ' of ' + total + ' \u2014 auto-generated by `osm pr-split`.');
        lines.push('');

        // GitHub Stack Map Navigation Table
        lines.push('### \ud83e\udd5e Stack Map (' + (splitIndex + 1) + '/' + total + ')');
        lines.push('');
        lines.push('| Layer | Part | Branch | Focus | Base |');
        lines.push('| :---: | :---: | :--- | :--- | :--- |');
        for (var i = 0; i < total; i++) {
            var s = plan.splits[i];
            var sBase = i === 0 ? baseBranch : plan.splits[i - 1].name;
            var isCurrent = (i === splitIndex);
            var marker = isCurrent ? '\ud83d\udc49' : ' ';
            var partStr = isCurrent ? '**' + (i + 1) + '**' : String(i + 1);
            var branchStr = isCurrent ? '**`' + s.name + '`**' : '`' + s.name + '`';
            var focusRaw = s.title || s.message || ('Part ' + (i + 1));
            var focusFirstLine = String(focusRaw).split(/\r?\n/)[0].trim();
            var focusSafe = focusFirstLine.replace(/\|/g, '\\|');
            var focusStr = isCurrent ? '**' + focusSafe + '**' : focusSafe;
            var baseStr = '`' + sBase + '`';
            lines.push('| ' + marker + ' | ' + partStr + ' | ' + branchStr + ' | ' + focusStr + ' | ' + baseStr + ' |');
        }
        lines.push('');

        // Stacking Guidance
        if (splitIndex < total - 1) {
            if (splitIndex === 0) {
                lines.push('> \u2139\ufe0f **Base of stack** \u2014 Targets `' + baseBranch + '`. Merge first. Next: `' + plan.splits[1].name + '`');
            } else {
                lines.push('> \u26a0\ufe0f **Stacked PR** \u2014 merge in order. Targets `' + base + '`. Next: `' + plan.splits[splitIndex + 1].name + '`');
            }
        } else {
            lines.push('> \u2705 **Last PR in stack** \u2014 Targets `' + base + '`. Merging this completes the split.');
        }
        lines.push('');

        // Summary
        if (split.summary) {
            lines.push('#### Summary');
            lines.push(split.summary);
            lines.push('');
        }

        // Commit-Loom Reviewer Note
        lines.push('> **Reviewer Note:** This PR is intentionally self-contained rather than atomic per Commit-Loom discipline. Multiple related changes have been rolled up because splitting them would leave intermediate states broken or uncompilable. Please review as a coherent unit.');
        lines.push('');

        // Design & Layering Rationale
        if (split.rationale) {
            lines.push('#### Design & Layering Rationale');
            lines.push(split.rationale);
            lines.push('');
        }

        // Key Changes
        var hasKeyChanges = split.keyChanges && (!Array.isArray(split.keyChanges) || split.keyChanges.length > 0);
        if (hasKeyChanges) {
            lines.push('#### Key Changes');
            if (Array.isArray(split.keyChanges)) {
                for (var k = 0; k < split.keyChanges.length; k++) {
                    lines.push('- ' + split.keyChanges[k]);
                }
            } else {
                lines.push(String(split.keyChanges));
            }
            lines.push('');
        }

        // Files List
        lines.push('**Files:**');
        if (split.files && Array.isArray(split.files)) {
            for (var j = 0; j < split.files.length; j++) {
                lines.push('- `' + split.files[j] + '`');
            }
        }
        lines.push('');

        // Verification
        var verifyCmd = split.verificationSteps || plan.verifyCommand;
        if (verifyCmd) {
            lines.push('#### Verification');
            lines.push('To independently verify this layer in isolation:');
            lines.push('```bash');
            lines.push(verifyCmd);
            lines.push('```');
            lines.push('');
        }

        // Footer
        lines.push('---');
        lines.push('*Generated by [`osm pr-split`](https://github.com/joeycumines/one-shot-man) using Commit-Loom methodology.*');

        return lines.join('\n');
    }

    // --- createPRs — pushes branches and creates stacked GitHub PRs ---
    // Options:
    //   draft:       bool   - Create as draft PRs (default: true)
    //   remote:      string - Git remote to push to (default: 'origin')
    //   pushOnly:    bool   - Push branches but don't create PRs
    //   autoMerge:   bool   - Enable auto-merge via merge queue
    //   mergeMethod: string - Merge method: squash, merge, rebase
    async function createPRs(plan, options) {
        options = options || {};
        var resolveDir = prSplit._resolveDir;
        var dir = resolveDir(plan.dir || '.');
        var draft = options.draft !== false;
        var remote = options.remote || 'origin';
        var pushOnly = options.pushOnly || false;
        var autoMerge = options.autoMerge || false;
        var mergeMethod = options.mergeMethod || 'squash';
        var dryRun = options.dryRun || false;

        if (!plan.splits || plan.splits.length === 0) {
            return { error: 'no splits in plan — run "plan" or "run" to generate splits first', results: [] };
        }

        // T077: Dry-run mode — simulate all operations, no real git/gh calls.
        if (dryRun) {
            var dryResults = [];
            for (var d = 0; d < plan.splits.length; d++) {
                var drySplit = plan.splits[d];
                var dryBase = d === 0 ? plan.baseBranch : plan.splits[d - 1].name;
                dryResults.push({
                    name: drySplit.name,
                    pushed: false,
                    prUrl: '',
                    error: null,
                    dryRun: true,
                    dryRunMsg: '[DRY RUN] Would push ' + drySplit.name +
                        (pushOnly ? '' : ' and create PR (base: ' + dryBase + ')')
                });
            }
            return { error: null, results: dryResults, dryRun: true };
        }

        // Late-bound references for mockability.
        var gitExec = prSplit._gitExec;
        var exec = prSplit._modules.exec;

        // Verify gh CLI is available (unless push-only mode).
        if (!pushOnly) {
            var ghCheck = await exec.execv(['gh', '--version']);
            if (ghCheck.code !== 0) {
                return { error: 'gh CLI not found — install GitHub CLI (https://cli.github.com) or use --push-only', results: [] };
            }
        }

        // Pre-flight: verify baseBranch exists on the remote so we don't
        // hit "Base sha can't be blank" from the GitHub GraphQL API.
        if (!pushOnly) {
            var remoteCheck = await gitExec(dir, ['ls-remote', '--heads', remote, plan.baseBranch]);
            if (remoteCheck.code !== 0 || remoteCheck.stdout.trim() === '') {
                return {
                    error: 'base branch "' + plan.baseBranch + '" not found on remote "' + remote + '" — push it first or check the branch name',
                    results: []
                };
            }
        }

        var results = [];

        // Step 1: Push all split branches.
        for (var i = 0; i < plan.splits.length; i++) {
            var split = plan.splits[i];
            var pushResult = await gitExec(dir, ['push', '-f', remote, split.name]);
            if (pushResult.code !== 0) {
                results.push({
                    name: split.name,
                    pushed: false,
                    prUrl: '',
                    error: 'push failed: ' + pushResult.stderr.trim()
                });
                return { error: 'push failed for ' + split.name + ': ' + pushResult.stderr.trim(), results: results };
            }
            results.push({
                name: split.name,
                pushed: true,
                prUrl: '',
                error: null
            });
        }

        if (pushOnly) {
            return { error: null, results: results };
        }

        // Step 2: Create PRs, stacked.
        for (var pi = 0; pi < plan.splits.length; pi++) {
            var prSplit2 = plan.splits[pi];
            var base = pi === 0 ? plan.baseBranch : plan.splits[pi - 1].name;
            var title = formatPRTitle(plan, pi);
            var body = formatPRBody(plan, pi);

            var ghArgs = ['gh', 'pr', 'create',
                '--base', base,
                '--head', prSplit2.name,
                '--title', title,
                '--body', body
            ];
            if (draft) {
                ghArgs.push('--draft');
            }

            // Pre-check: verify the head branch has actual changes from
            // the base. This avoids the GraphQL error "No commits between
            // base and head" / "Head sha can't be blank" which occurs when
            // execute-split fell back to --allow-empty.
            var diffCheck = await gitExec(dir, ['diff', '--quiet', base, prSplit2.name]);
            if (diffCheck.code === 0) {
                // Exit code 0 means no diff — skip PR creation.
                results[pi].error = null;
                results[pi].skipped = true;
                results[pi].skipReason = 'no changes between "' + base + '" and "' + prSplit2.name + '" — skipping PR creation';
                continue;
            }

            var ghResult = await exec.execv(ghArgs);
            if (ghResult.code !== 0) {
                results[pi].error = 'gh pr create failed: ' + ghResult.stderr.trim();
            } else {
                results[pi].prUrl = ghResult.stdout.trim();
            }
        }

        // Step 3: Auto-merge via merge queue (if enabled).
        if (autoMerge) {
            for (var k = 0; k < plan.splits.length; k++) {
                var splitForMerge = plan.splits[k];
                if (results[k].error) continue;
                var mergeArgs = ['gh', 'pr', 'merge', splitForMerge.name,
                    '--' + mergeMethod,
                    '--auto'
                ];
                var mergeResult = await exec.execv(mergeArgs);
                if (mergeResult.code !== 0) {
                    results[k].mergeError = 'auto-merge failed: ' + mergeResult.stderr.trim();
                } else {
                    results[k].autoMerge = true;
                }
            }
        }

        return { error: null, results: results };
    }

    // --- Exports ---
    prSplit.formatPRTitle = formatPRTitle;
    prSplit.formatPRBody = formatPRBody;
    prSplit.createPRs = createPRs;

    // --- createPRsAsync — non-blocking variant for TUI use (T076) ---
    // Identical logic to createPRs but uses exec.spawn via _gitExecAsync
    // and a local ghExecAsync helper instead of blocking exec.execv.
    // This keeps the Goja event loop free so BubbleTea can continue
    // rendering and processing events during push/PR/merge operations.
    //
    // Additional options over createPRs:
    //   progressFn(msg)  — callback for per-step progress updates
    //
    // The synchronous createPRs is preserved for REPL / CLI / test usage.

    // ghExecAsync — spawn 'gh' with args array, collect stdout+stderr,
    // return {stdout, stderr, code, error, message}.
    // Uses exec.spawn directly (not shell) to avoid quoting issues
    // with PR titles/bodies that contain special characters.
    async function ghExecAsync(args, options) {
        var exec = prSplit._modules.exec;
        var outputFn = (options && typeof options.outputFn === 'function') ? options.outputFn : null;
        if (!outputFn && typeof prSplit._outputCaptureFn === 'function') {
            outputFn = prSplit._outputCaptureFn;
        }
        if (outputFn) outputFn('\u276f gh ' + args.join(' '));

        var child = await exec.spawn('gh', args);

        async function readAll(stream, streamOutputFn) {
            var buf = '';
            while (true) {
                var chunk = await stream.read();
                if (chunk.done) break;
                if (chunk.value !== undefined && chunk.value !== null) {
                    var chunkStr = String(chunk.value);
                    buf += chunkStr;
                    if (streamOutputFn) {
                        var lines = chunkStr.split('\n');
                        for (var cl = 0; cl < lines.length; cl++) {
                            var line = lines[cl];
                            if (cl === lines.length - 1 && line === '') continue;
                            streamOutputFn(line);
                        }
                    }
                }
            }
            return buf;
        }

        var results = await Promise.all([
            readAll(child.stdout, outputFn),
            readAll(child.stderr, outputFn),
            child.wait()
        ]);
        var code = (results[2] && results[2].code !== undefined) ? results[2].code : 0;
        return {
            stdout: results[0],
            stderr: results[1],
            code: code,
            error: code !== 0,
            message: code !== 0 ? 'exit status ' + code : ''
        };
    }

    async function createPRsAsync(plan, options) {
        options = options || {};
        var resolveDir = prSplit._resolveDir;
        var dir = resolveDir(plan.dir || '.');
        var draft = options.draft !== false;
        var remote = options.remote || 'origin';
        var pushOnly = options.pushOnly || false;
        var autoMerge = options.autoMerge || false;
        var mergeMethod = options.mergeMethod || 'squash';
        var progressFn = options.progressFn || null;
        var dryRun = options.dryRun || false;

        if (!plan.splits || plan.splits.length === 0) {
            return { error: 'no splits in plan \u2014 run "plan" or "run" to generate splits first', results: [] };
        }

        // T077: Dry-run mode — simulate all operations, no real git/gh calls.
        if (dryRun) {
            var dryResults = [];
            for (var d = 0; d < plan.splits.length; d++) {
                var drySplit = plan.splits[d];
                var dryBase = d === 0 ? plan.baseBranch : plan.splits[d - 1].name;
                if (progressFn) progressFn('[DRY RUN] ' + (d + 1) + '/' + plan.splits.length + ': ' + drySplit.name);
                dryResults.push({
                    name: drySplit.name,
                    pushed: false,
                    prUrl: '',
                    error: null,
                    dryRun: true,
                    dryRunMsg: '[DRY RUN] Would push ' + drySplit.name +
                        (pushOnly ? '' : ' and create PR (base: ' + dryBase + ')')
                });
            }
            return { error: null, results: dryResults, dryRun: true };
        }

        var gitExecAsync = prSplit._gitExecAsync;

        // Pre-flight: verify gh CLI is available.
        if (!pushOnly) {
            if (progressFn) progressFn('Checking gh CLI availability\u2026');
            var ghCheck = await ghExecAsync(['--version']);
            if (ghCheck.code !== 0) {
                return { error: 'gh CLI not found \u2014 install GitHub CLI (https://cli.github.com) or use --push-only', results: [] };
            }
        }

        // Pre-flight: verify baseBranch exists on the remote.
        if (!pushOnly) {
            if (progressFn) progressFn('Verifying base branch "' + plan.baseBranch + '" on remote\u2026');
            var remoteCheck = await gitExecAsync(dir, ['ls-remote', '--heads', remote, plan.baseBranch]);
            if (remoteCheck.code !== 0 || remoteCheck.stdout.trim() === '') {
                return {
                    error: 'base branch "' + plan.baseBranch + '" not found on remote "' + remote + '" \u2014 push it first or check the branch name',
                    results: []
                };
            }
        }

        // Cancellation check helper.
        function cancelled() {
            return (typeof prSplit.isCancelled === 'function' && prSplit.isCancelled()) ||
                (typeof prSplit.isForceCancelled === 'function' && prSplit.isForceCancelled());  // T117: honor force-cancel
        }

        var results = [];
        var total = plan.splits.length;

        // Step 1: Push all split branches.
        for (var i = 0; i < total; i++) {
            if (cancelled()) return { error: 'cancelled by user', results: results };
            var split = plan.splits[i];
            if (progressFn) progressFn('Pushing ' + (i + 1) + '/' + total + ': ' + split.name);
            var pushResult = await gitExecAsync(dir, ['push', '-f', remote, split.name]);
            if (pushResult.code !== 0) {
                results.push({
                    name: split.name,
                    pushed: false,
                    prUrl: '',
                    error: 'push failed: ' + pushResult.stderr.trim()
                });
                return { error: 'push failed for ' + split.name + ': ' + pushResult.stderr.trim(), results: results };
            }
            results.push({
                name: split.name,
                pushed: true,
                prUrl: '',
                error: null
            });
        }

        if (pushOnly) {
            return { error: null, results: results };
        }

        // Step 2: Create PRs, stacked.
        for (var pi = 0; pi < total; pi++) {
            if (cancelled()) return { error: 'cancelled by user', results: results };
            var prSplit2 = plan.splits[pi];
            var base = pi === 0 ? plan.baseBranch : plan.splits[pi - 1].name;
            if (progressFn) progressFn('Creating PR ' + (pi + 1) + '/' + total + ': ' + prSplit2.name);
            var title = formatPRTitle(plan, pi);
            var body = formatPRBody(plan, pi);

            // Pre-check: verify the head branch has actual changes from
            // the base. Avoids GraphQL error "No commits between base and head".
            var diffCheck = await gitExecAsync(dir, ['diff', '--quiet', base, prSplit2.name]);
            if (diffCheck.code === 0) {
                // Exit code 0 means no diff — skip PR creation.
                results[pi].error = null;
                results[pi].skipped = true;
                results[pi].skipReason = 'no changes between "' + base + '" and "' + prSplit2.name + '" \u2014 skipping PR creation';
                continue;
            }

            var ghArgs = ['pr', 'create',
                '--base', base,
                '--head', prSplit2.name,
                '--title', title,
                '--body', body
            ];
            if (draft) {
                ghArgs.push('--draft');
            }

            var ghResult = await ghExecAsync(ghArgs);
            if (ghResult.code !== 0) {
                results[pi].error = 'gh pr create failed: ' + ghResult.stderr.trim();
            } else {
                results[pi].prUrl = ghResult.stdout.trim();
            }
        }

        // Step 3: Auto-merge via merge queue (if enabled).
        if (autoMerge) {
            for (var k = 0; k < total; k++) {
                if (cancelled()) return { error: 'cancelled by user', results: results };
                var splitForMerge = plan.splits[k];
                if (results[k].error || results[k].skipped) continue;
                if (progressFn) progressFn('Enabling auto-merge ' + (k + 1) + '/' + total + ': ' + splitForMerge.name);
                var mergeArgs = ['pr', 'merge', splitForMerge.name,
                    '--' + mergeMethod,
                    '--auto'
                ];
                var mergeResult = await ghExecAsync(mergeArgs);
                if (mergeResult.code !== 0) {
                    results[k].mergeError = 'auto-merge failed: ' + mergeResult.stderr.trim();
                } else {
                    results[k].autoMerge = true;
                }
            }
        }

        return { error: null, results: results };
    }

    prSplit.createPRsAsync = createPRsAsync;
})(globalThis.prSplit);
